services:
  app:
    image: cleitonsocodolski/rate-limiter:latest
    ports: 
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"    