services:
  ratelimiter:
    build: .
    ports: 
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"    